### ISSUE TITLE
[terraform] Rename resources to avoid clashes with other solutions

### ISSUE THREAD

**Issue by davidcavazos** [GoogleCloudPlatform/terraform-genai-knowledge-base#84]
Some resource names can be very generic like `webhook` and can clash with resources created by other solutions. We should go over all the resource names and give them a unique prefix to make sure they don't clash.

After this, we can revert #83 and set `unique_names` to false to have nicer names in the deployment.

**Comment by kweinmeister** [comment]
@davidcavazos we already backed this out, as `unique_names` was causing the names of resources to not match the Neos tutorial.

https://github.com/GoogleCloudPlatform/terraform-genai-knowledge-base/pull/87
